services:
  - type: web
    name: next-js
    env: node
    plan: starter
    buildCommand: npm i; npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production